<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pizzes [
<!ELEMENT pizzes (ingredients, categories)>
    <!ELEMENT ingredients (ingredient)*>
        <!ELEMENT ingredient (#PCDATA)>
        <!ATTLIST ingredient codi ID #REQUIRED>
    <!ELEMENT categories (categoria)*>
        <!ELEMENT categoria EMPTY>
            <!ATTLIST categoria nom CDATA #REQUIRED>
            <!ATTLIST categoria ingredients IDREFS #REQUIRED>
]>

<pizzes>
    <ingredients>
        <ingredient codi="213" > Tomaquet </ingredient>
        <ingredient codi="142" > Massa</ingredient>
        <ingredient codi="423" > Formatge </ingredient>
        <ingredient codi="333" > Pernil </ingredient>
    
    </ingredients>
    <categories>
        <categoria nom="Pizza de pernil" ingredients="Pernil,Massa,Tomaquet,Pernil" ></categoria>
    
    </categories>

</pizzes>